import { useMemo, useState, type FormEvent } from 'react'
import { Icon } from './Icon'

// Prototype rows reproduce A12/A13 only. They are not records from M-TEAM.
const FIGMA_EVENTS = [
  { title:'Torneo interno de Crossfit',date:'19/09/2026 · 10:00',place:'Sede Villa Urquiza',status:'Publicado',startsAt:'2026-09-19T10:00' },
  { title:'Clase abierta de Zumba',date:'25/09/2026 · 19:00',place:'Sede Belgrano',status:'Publicado',startsAt:'2026-09-25T19:00' },
  { title:'Charla de nutrición deportiva',date:'07/10/2026 · 20:00',place:'Sede Belgrano',status:'Borrador',startsAt:'2026-10-07T20:00' },
  { title:'Maratón M-TEAM 5K',date:'30/08/2026 · 09:00',place:'Parque Saavedra',status:'Finalizado',startsAt:'2026-08-30T09:00' },
  { title:'Jornada de puertas abiertas',date:'22/08/2026 · 11:00',place:'Sede Villa Urquiza',status:'Cancelado',startsAt:'2026-08-22T11:00' },
]
const FIGMA_NEWS = [
  { title:'Feriado del 8 de septiembre',audience:'Todos',date:'06/09/2026',status:'Publicada' },
  { title:'Nueva clase de Boxeo en Belgrano',audience:'Todos',date:'05/09/2026',status:'Publicada' },
  { title:'Mantenimiento de vestuarios',audience:'Socios',date:'03/09/2026',status:'Publicada' },
  { title:'Reunión de entrenadores',audience:'Entrenadores',date:'02/09/2026',status:'Publicada' },
  { title:'Cambio de horario de verano',audience:'Todos',date:'—',status:'Borrador' },
]

export function AdminEventsScreen({ onUnavailable }: { onUnavailable: (message:string)=>void }) {
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('Todos')
  const [branch,setBranch]=useState('Todas')
  const rows=useMemo(()=>FIGMA_EVENTS.map(item=>({...item,status:adminEventStatus(item)})).filter(item=>`${item.title} ${item.place}`.toLowerCase().includes(query.toLowerCase())&&(status==='Todos'||item.status===status)&&(branch==='Todas'||item.place.includes(branch))),[query,status,branch])
  function act(action:string,title:string){onUnavailable(`La acción “${action}” sobre “${title}” requiere el servicio de eventos. No se guardaron cambios.`)}
  return <section className="admin-list-layout"><div className="admin-list-main"><p className="page-intro">Guardá como borrador, publicá o cancelá. Un evento cancelado se conserva y genera una notificación.</p><div className="toolbar admin-list-toolbar"><label className="search-shell"><Icon name="search"/><input placeholder="Buscar evento" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Filtrar eventos por estado" value={status} onChange={event=>setStatus(event.target.value)}><option>Todos</option><option>Publicado</option><option>Borrador</option><option>Finalizado</option><option>Cancelado</option></select><select aria-label="Filtrar eventos por sede" value={branch} onChange={event=>setBranch(event.target.value)}><option value="Todas">Sede: todas</option><option>Villa Urquiza</option><option>Belgrano</option></select></div><div className="table-scroll surface-card"><table className="data-table"><thead><tr><th>Evento</th><th>Fecha y horario</th><th>Ubicación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(item=><tr key={item.title}><td>{item.title}</td><td>{item.date}</td><td>{item.place}</td><td><StatusBadge status={item.status}/></td><td><div className="table-actions">{item.status==='Finalizado'||item.status==='Cancelado'?<button className="button button-secondary" onClick={()=>act('Ver',item.title)}>Ver</button>:<><button className="button button-secondary" onClick={()=>act('Editar',item.title)}>Editar</button>{item.status==='Borrador'?<button className="button button-primary" onClick={()=>act('Publicar',item.title)}>Publicar</button>:<button className="button button-danger-outline" onClick={()=>act('Cancelar',item.title)}>Cancelar</button>}</>}</div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><p>No hay eventos que coincidan con los filtros.</p></div>}</div></div></section>
}

export function AdminNewsScreen({ notice, onSubmit, onUnavailable }: { notice:string; onSubmit:(event:FormEvent<HTMLFormElement>)=>void; onUnavailable:(message:string)=>void }) {
  const [query,setQuery]=useState('')
  const [audience,setAudience]=useState('Todas')
  const [status,setStatus]=useState('Todos')
  const rows=useMemo(()=>FIGMA_NEWS.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())&&(audience==='Todas'||item.audience===audience)&&(status==='Todos'||item.status===status)),[query,audience,status])
  return <div className="admin-news-layout"><section className="admin-news-list"><p className="page-intro">Cada publicación puede dirigirse a todos, solo a socios o solo a entrenadores.</p><div className="toolbar admin-list-toolbar"><label className="search-shell"><Icon name="search"/><input placeholder="Buscar novedad" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Filtrar novedades por audiencia" value={audience} onChange={event=>setAudience(event.target.value)}><option>Todas</option><option>Todos</option><option>Socios</option><option>Entrenadores</option></select><select aria-label="Filtrar novedades por estado" value={status} onChange={event=>setStatus(event.target.value)}><option>Todos</option><option>Publicada</option><option>Borrador</option><option>Desactivada</option></select></div><div className="table-scroll surface-card"><table className="data-table"><thead><tr><th>Título</th><th>Audiencia</th><th>Publicada</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(item=><tr key={item.title}><td>{item.title}</td><td>{item.audience}</td><td>{item.date}</td><td><StatusBadge status={item.status}/></td><td><div className="table-actions"><button className="button button-secondary" onClick={()=>onUnavailable(`Editar “${item.title}” requiere el servicio de novedades. No se guardaron cambios.`)}>Editar</button>{item.status==='Publicada'?<button className="button button-danger-outline" onClick={()=>onUnavailable(`Desactivar “${item.title}” requiere el servicio de novedades. No se guardaron cambios.`)}>Desactivar</button>:<button className="button button-primary" onClick={()=>onUnavailable(`Publicar “${item.title}” requiere el servicio de novedades. No se guardaron cambios.`)}>Publicar</button>}</div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><p>No hay novedades que coincidan con los filtros.</p></div>}</div></section><aside className="surface-card admin-news-editor"><h2>Nueva novedad</h2><form onSubmit={onSubmit}><label className="read-field"><span>Título</span><input placeholder="Ej.: Feriado del 8 de septiembre" required/></label><label className="read-field"><span>Contenido</span><textarea rows={5} placeholder="Escribí acá el texto que van a leer los usuarios…" required/></label><fieldset><legend>Audiencia</legend><div className="audience-options">{['Todos','Socios','Entrenadores'].map(item=><label key={item}><input type="radio" name="audience" value={item} defaultChecked={item==='Todos'}/><span>{item}</span></label>)}</div></fieldset>{notice&&<p className="notice-inline" role="status">{notice}</p>}<div className="admin-editor-actions"><button className="button button-secondary" type="submit" name="status" value="draft">Guardar borrador</button><button className="button button-primary" type="submit" name="status" value="publish">Publicar</button></div></form></aside></div>
}

function StatusBadge({status}:{status:string}){const tone=status==='Publicado'||status==='Publicada'?'badge-info':status==='Borrador'?'badge-secondary':status==='Cancelado'?'badge-disabled':'badge-neutral';return <span className={`badge ${tone}`}>{status}</span>}
function adminEventStatus(event:typeof FIGMA_EVENTS[number]){if(event.status==='Cancelado'||event.status==='Borrador')return event.status;return new Date(event.startsAt).getTime()<Date.now()?'Finalizado':'Publicado'}
