import {
  ArrowRight,
  Bell,
  Building,
  CalendarDays,
  Camera,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock3,
  Info,
  Copy,
  Dumbbell,
  Ellipsis,
  Eye,
  FileText,
  House,
  Image,
  LockKeyhole,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  Menu,
  Pencil,
  Phone,
  Plus,
  QrCode,
  RefreshCw,
  Search,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  Users,
  Wallet,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'

export type IconName = 'home' | 'user' | 'users' | 'wallet' | 'file' | 'qr' | 'calendar' | 'map' | 'pin' | 'clock' | 'phone' | 'bell' | 'megaphone' | 'trophy' | 'image' | 'search' | 'filter' | 'plus' | 'chevron' | 'logout' | 'check' | 'alert' | 'chart' | 'building' | 'dumbbell' | 'edit' | 'more' | 'close' | 'menu' | 'eye' | 'mail' | 'lock' | 'arrow' | 'copy' | 'back' | 'next' | 'down' | 'refresh' | 'camera' | 'upload' | 'trash' | 'info'

const ICONS: Record<IconName, LucideIcon> = {
  home: House,
  user: User,
  users: Users,
  wallet: Wallet,
  file: FileText,
  qr: QrCode,
  calendar: CalendarDays,
  map: MapIcon,
  pin: MapPin,
  clock: Clock3,
  phone: Phone,
  bell: Bell,
  megaphone: Megaphone,
  trophy: Trophy,
  image: Image,
  search: Search,
  filter: SlidersHorizontal,
  plus: Plus,
  chevron: ChevronRight,
  logout: LogOut,
  check: Check,
  alert: TriangleAlert,
  chart: ChartNoAxesColumnIncreasing,
  building: Building,
  dumbbell: Dumbbell,
  edit: Pencil,
  more: Ellipsis,
  close: X,
  menu: Menu,
  eye: Eye,
  mail: Mail,
  lock: LockKeyhole,
  arrow: ArrowRight,
  copy: Copy,
  back: ChevronLeft,
  next: ChevronRight,
  down: ChevronDown,
  refresh: RefreshCw,
  camera: Camera,
  upload: Upload,
  trash: Trash2,
  info: Info,
}

export function Icon({ name, size = 20, ...props }: { name: IconName; size?: number } & LucideProps) {
  const Component = ICONS[name]
  return <Component aria-hidden="true" size={size} strokeWidth={1.7} {...props} />
}
